apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gcemachineproviderspecs.gceproviderconfig.k8s.io
spec:
  group: gceproviderconfig.k8s.io
  names:
    kind: GCEMachineProviderSpec
    plural: gcemachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        disks:
          items:
            properties:
              initializeParams:
                properties:
                  diskSizeGb:
                    format: int64
                    type: integer
                  diskType:
                    type: string
                required:
                - diskSizeGb
                - diskType
                type: object
            required:
            - initializeParams
            type: object
          type: array
        instanceTemplate:
          type: string
        kind:
          type: string
        machineType:
          type: string
        metadata:
          type: object
        os:
          type: string
        roles:
          items:
            type: string
          type: array
        zone:
          type: string
      required:
      - zone
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
