# permissions for end users to view gkeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gkecluster-viewer-role
rules:
- apiGroups:
  - infra.cluster.x-k8s.io
  resources:
  - gkeclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.cluster.x-k8s.io
  resources:
  - gkeclusters/status
  verbs:
  - get
