/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command docgen writes the table of supported add-ons that the book includes, so the documentation is
// rendered from addons.Supported rather than kept in step with it by hand.
package main

import (
	"bytes"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/olekukonko/tablewriter"
	"github.com/olekukonko/tablewriter/renderer"
	"github.com/olekukonko/tablewriter/tw"

	"sigs.k8s.io/cluster-api-provider-gcp/exp/api/v1beta1/addons"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: docgen <output file>")
		os.Exit(2)
	}

	out, err := render()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(os.Args[1], out, 0o600); err != nil { //nolint:gosec // the path is the go:generate directive's
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// render lays the add-ons out as a Markdown table, sorted by key and with every column padded to one
// width so that editors treat it as already formatted.
func render() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("<!-- Code generated by docgen from addons.Supported. DO NOT EDIT. -->\n\n")

	table := tablewriter.NewTable(&out,
		tablewriter.WithRenderer(renderer.NewMarkdown()),
		tablewriter.WithRowAutoWrap(tw.WrapNone),
		tablewriter.WithHeaderAutoFormat(tw.Off),
		tablewriter.WithHeaderAlignment(tw.AlignLeft),
		tablewriter.WithRowAlignment(tw.AlignLeft),
	)
	table.Header("Key", "Enables", "Options", "Requires")

	sorted := slices.SortedFunc(slices.Values(addons.Supported), func(a, b addons.Addon) int {
		return strings.Compare(a.Key, b.Key)
	})
	for _, addon := range sorted {
		if err := table.Append(row(addon)); err != nil {
			return nil, err
		}
	}
	if err := table.Render(); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

// row is an add-on's cells: its key, linked to GKE's documentation where there is some, what it enables,
// its options, and its prerequisites in the order they are checked — at admission, then during
// reconciliation.
func row(addon addons.Addon) []string {
	key := "`" + addon.Key + "`"
	if addon.DocsURL != "" {
		key = fmt.Sprintf("[%s](%s)", key, addon.DocsURL)
	}

	options := make([]string, 0, len(addon.Options))
	for _, option := range addon.Options {
		options = append(options, fmt.Sprintf("`%s` — %s", option.Key, option.Description))
	}

	requires := make([]string, 0, len(addon.SpecConstraints)+len(addon.ClusterConstraints))
	for _, constraint := range addon.SpecConstraints {
		requires = append(requires, constraint.Describe())
	}
	for _, constraint := range addon.ClusterConstraints {
		requires = append(requires, constraint.Describe())
	}

	return []string{key, addon.Description, list(options), list(requires)}
}

// list renders items as an HTML list, since a Markdown table cell can't hold a Markdown one, standing in
// a dash when there are none.
func list(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	return "<ul><li>" + strings.Join(items, "</li><li>") + "</li></ul>"
}
