// +build !ignore_autogenerated_core_v1alpha3

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.20.2. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha4 "sigs.k8s.io/cluster-api-provider-gcp/api/v1alpha4"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AttachedDiskSpec)(nil), (*v1alpha4.AttachedDiskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AttachedDiskSpec_To_v1alpha4_AttachedDiskSpec(a.(*AttachedDiskSpec), b.(*v1alpha4.AttachedDiskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AttachedDiskSpec)(nil), (*AttachedDiskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AttachedDiskSpec_To_v1alpha3_AttachedDiskSpec(a.(*v1alpha4.AttachedDiskSpec), b.(*AttachedDiskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BuildParams)(nil), (*v1alpha4.BuildParams)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BuildParams_To_v1alpha4_BuildParams(a.(*BuildParams), b.(*v1alpha4.BuildParams), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.BuildParams)(nil), (*BuildParams)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_BuildParams_To_v1alpha3_BuildParams(a.(*v1alpha4.BuildParams), b.(*BuildParams), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Filter)(nil), (*v1alpha4.Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Filter_To_v1alpha4_Filter(a.(*Filter), b.(*v1alpha4.Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Filter)(nil), (*Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Filter_To_v1alpha3_Filter(a.(*v1alpha4.Filter), b.(*Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPCluster)(nil), (*v1alpha4.GCPCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPCluster_To_v1alpha4_GCPCluster(a.(*GCPCluster), b.(*v1alpha4.GCPCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPCluster)(nil), (*GCPCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPCluster_To_v1alpha3_GCPCluster(a.(*v1alpha4.GCPCluster), b.(*GCPCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPClusterList)(nil), (*v1alpha4.GCPClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPClusterList_To_v1alpha4_GCPClusterList(a.(*GCPClusterList), b.(*v1alpha4.GCPClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPClusterList)(nil), (*GCPClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPClusterList_To_v1alpha3_GCPClusterList(a.(*v1alpha4.GCPClusterList), b.(*GCPClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPMachine)(nil), (*v1alpha4.GCPMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachine_To_v1alpha4_GCPMachine(a.(*GCPMachine), b.(*v1alpha4.GCPMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPMachine)(nil), (*GCPMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachine_To_v1alpha3_GCPMachine(a.(*v1alpha4.GCPMachine), b.(*GCPMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPMachineList)(nil), (*v1alpha4.GCPMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineList_To_v1alpha4_GCPMachineList(a.(*GCPMachineList), b.(*v1alpha4.GCPMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPMachineList)(nil), (*GCPMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineList_To_v1alpha3_GCPMachineList(a.(*v1alpha4.GCPMachineList), b.(*GCPMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPMachineTemplate)(nil), (*v1alpha4.GCPMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineTemplate_To_v1alpha4_GCPMachineTemplate(a.(*GCPMachineTemplate), b.(*v1alpha4.GCPMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPMachineTemplate)(nil), (*GCPMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineTemplate_To_v1alpha3_GCPMachineTemplate(a.(*v1alpha4.GCPMachineTemplate), b.(*GCPMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPMachineTemplateList)(nil), (*v1alpha4.GCPMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineTemplateList_To_v1alpha4_GCPMachineTemplateList(a.(*GCPMachineTemplateList), b.(*v1alpha4.GCPMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPMachineTemplateList)(nil), (*GCPMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineTemplateList_To_v1alpha3_GCPMachineTemplateList(a.(*v1alpha4.GCPMachineTemplateList), b.(*GCPMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPMachineTemplateResource)(nil), (*v1alpha4.GCPMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineTemplateResource_To_v1alpha4_GCPMachineTemplateResource(a.(*GCPMachineTemplateResource), b.(*v1alpha4.GCPMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPMachineTemplateResource)(nil), (*GCPMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineTemplateResource_To_v1alpha3_GCPMachineTemplateResource(a.(*v1alpha4.GCPMachineTemplateResource), b.(*GCPMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPMachineTemplateSpec)(nil), (*v1alpha4.GCPMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineTemplateSpec_To_v1alpha4_GCPMachineTemplateSpec(a.(*GCPMachineTemplateSpec), b.(*v1alpha4.GCPMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.GCPMachineTemplateSpec)(nil), (*GCPMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineTemplateSpec_To_v1alpha3_GCPMachineTemplateSpec(a.(*v1alpha4.GCPMachineTemplateSpec), b.(*GCPMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetadataItem)(nil), (*v1alpha4.MetadataItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetadataItem_To_v1alpha4_MetadataItem(a.(*MetadataItem), b.(*v1alpha4.MetadataItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetadataItem)(nil), (*MetadataItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetadataItem_To_v1alpha3_MetadataItem(a.(*v1alpha4.MetadataItem), b.(*MetadataItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Network)(nil), (*v1alpha4.Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Network_To_v1alpha4_Network(a.(*Network), b.(*v1alpha4.Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Network)(nil), (*Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Network_To_v1alpha3_Network(a.(*v1alpha4.Network), b.(*Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceAccount)(nil), (*v1alpha4.ServiceAccount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ServiceAccount_To_v1alpha4_ServiceAccount(a.(*ServiceAccount), b.(*v1alpha4.ServiceAccount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.ServiceAccount)(nil), (*ServiceAccount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ServiceAccount_To_v1alpha3_ServiceAccount(a.(*v1alpha4.ServiceAccount), b.(*ServiceAccount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetSpec)(nil), (*v1alpha4.SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(a.(*SubnetSpec), b.(*v1alpha4.SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SubnetSpec)(nil), (*SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(a.(*v1alpha4.SubnetSpec), b.(*SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha3.APIEndpoint)(nil), (*apiv1alpha4.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*apiv1alpha3.APIEndpoint), b.(*apiv1alpha4.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*GCPClusterSpec)(nil), (*v1alpha4.GCPClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPClusterSpec_To_v1alpha4_GCPClusterSpec(a.(*GCPClusterSpec), b.(*v1alpha4.GCPClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*GCPClusterStatus)(nil), (*v1alpha4.GCPClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPClusterStatus_To_v1alpha4_GCPClusterStatus(a.(*GCPClusterStatus), b.(*v1alpha4.GCPClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*GCPMachineSpec)(nil), (*v1alpha4.GCPMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineSpec_To_v1alpha4_GCPMachineSpec(a.(*GCPMachineSpec), b.(*v1alpha4.GCPMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*GCPMachineStatus)(nil), (*v1alpha4.GCPMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_GCPMachineStatus_To_v1alpha4_GCPMachineStatus(a.(*GCPMachineStatus), b.(*v1alpha4.GCPMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*NetworkSpec)(nil), (*v1alpha4.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha4.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha4.APIEndpoint)(nil), (*apiv1alpha3.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*apiv1alpha4.APIEndpoint), b.(*apiv1alpha3.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.GCPClusterSpec)(nil), (*GCPClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPClusterSpec_To_v1alpha3_GCPClusterSpec(a.(*v1alpha4.GCPClusterSpec), b.(*GCPClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.GCPClusterStatus)(nil), (*GCPClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPClusterStatus_To_v1alpha3_GCPClusterStatus(a.(*v1alpha4.GCPClusterStatus), b.(*GCPClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.GCPMachineSpec)(nil), (*GCPMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineSpec_To_v1alpha3_GCPMachineSpec(a.(*v1alpha4.GCPMachineSpec), b.(*GCPMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.GCPMachineStatus)(nil), (*GCPMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_GCPMachineStatus_To_v1alpha3_GCPMachineStatus(a.(*v1alpha4.GCPMachineStatus), b.(*GCPMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(a.(*v1alpha4.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_AttachedDiskSpec_To_v1alpha4_AttachedDiskSpec(in *AttachedDiskSpec, out *v1alpha4.AttachedDiskSpec, s conversion.Scope) error {
	out.DeviceType = (*v1alpha4.DiskType)(unsafe.Pointer(in.DeviceType))
	out.Size = (*int64)(unsafe.Pointer(in.Size))
	return nil
}

// Convert_v1alpha3_AttachedDiskSpec_To_v1alpha4_AttachedDiskSpec is an autogenerated conversion function.
func Convert_v1alpha3_AttachedDiskSpec_To_v1alpha4_AttachedDiskSpec(in *AttachedDiskSpec, out *v1alpha4.AttachedDiskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AttachedDiskSpec_To_v1alpha4_AttachedDiskSpec(in, out, s)
}

func autoConvert_v1alpha4_AttachedDiskSpec_To_v1alpha3_AttachedDiskSpec(in *v1alpha4.AttachedDiskSpec, out *AttachedDiskSpec, s conversion.Scope) error {
	out.DeviceType = (*DiskType)(unsafe.Pointer(in.DeviceType))
	out.Size = (*int64)(unsafe.Pointer(in.Size))
	return nil
}

// Convert_v1alpha4_AttachedDiskSpec_To_v1alpha3_AttachedDiskSpec is an autogenerated conversion function.
func Convert_v1alpha4_AttachedDiskSpec_To_v1alpha3_AttachedDiskSpec(in *v1alpha4.AttachedDiskSpec, out *AttachedDiskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AttachedDiskSpec_To_v1alpha3_AttachedDiskSpec(in, out, s)
}

func autoConvert_v1alpha3_BuildParams_To_v1alpha4_BuildParams(in *BuildParams, out *v1alpha4.BuildParams, s conversion.Scope) error {
	out.Lifecycle = v1alpha4.ResourceLifecycle(in.Lifecycle)
	out.ClusterName = in.ClusterName
	out.ResourceID = in.ResourceID
	out.Role = (*string)(unsafe.Pointer(in.Role))
	out.Additional = *(*v1alpha4.Labels)(unsafe.Pointer(&in.Additional))
	return nil
}

// Convert_v1alpha3_BuildParams_To_v1alpha4_BuildParams is an autogenerated conversion function.
func Convert_v1alpha3_BuildParams_To_v1alpha4_BuildParams(in *BuildParams, out *v1alpha4.BuildParams, s conversion.Scope) error {
	return autoConvert_v1alpha3_BuildParams_To_v1alpha4_BuildParams(in, out, s)
}

func autoConvert_v1alpha4_BuildParams_To_v1alpha3_BuildParams(in *v1alpha4.BuildParams, out *BuildParams, s conversion.Scope) error {
	out.Lifecycle = ResourceLifecycle(in.Lifecycle)
	out.ClusterName = in.ClusterName
	out.ResourceID = in.ResourceID
	out.Role = (*string)(unsafe.Pointer(in.Role))
	out.Additional = *(*Labels)(unsafe.Pointer(&in.Additional))
	return nil
}

// Convert_v1alpha4_BuildParams_To_v1alpha3_BuildParams is an autogenerated conversion function.
func Convert_v1alpha4_BuildParams_To_v1alpha3_BuildParams(in *v1alpha4.BuildParams, out *BuildParams, s conversion.Scope) error {
	return autoConvert_v1alpha4_BuildParams_To_v1alpha3_BuildParams(in, out, s)
}

func autoConvert_v1alpha3_Filter_To_v1alpha4_Filter(in *Filter, out *v1alpha4.Filter, s conversion.Scope) error {
	out.Name = in.Name
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha3_Filter_To_v1alpha4_Filter is an autogenerated conversion function.
func Convert_v1alpha3_Filter_To_v1alpha4_Filter(in *Filter, out *v1alpha4.Filter, s conversion.Scope) error {
	return autoConvert_v1alpha3_Filter_To_v1alpha4_Filter(in, out, s)
}

func autoConvert_v1alpha4_Filter_To_v1alpha3_Filter(in *v1alpha4.Filter, out *Filter, s conversion.Scope) error {
	out.Name = in.Name
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha4_Filter_To_v1alpha3_Filter is an autogenerated conversion function.
func Convert_v1alpha4_Filter_To_v1alpha3_Filter(in *v1alpha4.Filter, out *Filter, s conversion.Scope) error {
	return autoConvert_v1alpha4_Filter_To_v1alpha3_Filter(in, out, s)
}

func autoConvert_v1alpha3_GCPCluster_To_v1alpha4_GCPCluster(in *GCPCluster, out *v1alpha4.GCPCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_GCPClusterSpec_To_v1alpha4_GCPClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_GCPClusterStatus_To_v1alpha4_GCPClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_GCPCluster_To_v1alpha4_GCPCluster is an autogenerated conversion function.
func Convert_v1alpha3_GCPCluster_To_v1alpha4_GCPCluster(in *GCPCluster, out *v1alpha4.GCPCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPCluster_To_v1alpha4_GCPCluster(in, out, s)
}

func autoConvert_v1alpha4_GCPCluster_To_v1alpha3_GCPCluster(in *v1alpha4.GCPCluster, out *GCPCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_GCPClusterSpec_To_v1alpha3_GCPClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_GCPClusterStatus_To_v1alpha3_GCPClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_GCPCluster_To_v1alpha3_GCPCluster is an autogenerated conversion function.
func Convert_v1alpha4_GCPCluster_To_v1alpha3_GCPCluster(in *v1alpha4.GCPCluster, out *GCPCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPCluster_To_v1alpha3_GCPCluster(in, out, s)
}

func autoConvert_v1alpha3_GCPClusterList_To_v1alpha4_GCPClusterList(in *GCPClusterList, out *v1alpha4.GCPClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.GCPCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_GCPCluster_To_v1alpha4_GCPCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_GCPClusterList_To_v1alpha4_GCPClusterList is an autogenerated conversion function.
func Convert_v1alpha3_GCPClusterList_To_v1alpha4_GCPClusterList(in *GCPClusterList, out *v1alpha4.GCPClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPClusterList_To_v1alpha4_GCPClusterList(in, out, s)
}

func autoConvert_v1alpha4_GCPClusterList_To_v1alpha3_GCPClusterList(in *v1alpha4.GCPClusterList, out *GCPClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_GCPCluster_To_v1alpha3_GCPCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_GCPClusterList_To_v1alpha3_GCPClusterList is an autogenerated conversion function.
func Convert_v1alpha4_GCPClusterList_To_v1alpha3_GCPClusterList(in *v1alpha4.GCPClusterList, out *GCPClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPClusterList_To_v1alpha3_GCPClusterList(in, out, s)
}

func autoConvert_v1alpha3_GCPClusterSpec_To_v1alpha4_GCPClusterSpec(in *GCPClusterSpec, out *v1alpha4.GCPClusterSpec, s conversion.Scope) error {
	out.Project = in.Project
	out.Region = in.Region
	if err := Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.FailureDomains = *(*[]string)(unsafe.Pointer(&in.FailureDomains))
	out.AdditionalLabels = *(*v1alpha4.Labels)(unsafe.Pointer(&in.AdditionalLabels))
	return nil
}

func autoConvert_v1alpha4_GCPClusterSpec_To_v1alpha3_GCPClusterSpec(in *v1alpha4.GCPClusterSpec, out *GCPClusterSpec, s conversion.Scope) error {
	out.Project = in.Project
	out.Region = in.Region
	if err := Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.FailureDomains = *(*[]string)(unsafe.Pointer(&in.FailureDomains))
	out.AdditionalLabels = *(*Labels)(unsafe.Pointer(&in.AdditionalLabels))
	return nil
}

func autoConvert_v1alpha3_GCPClusterStatus_To_v1alpha4_GCPClusterStatus(in *GCPClusterStatus, out *v1alpha4.GCPClusterStatus, s conversion.Scope) error {
	out.FailureDomains = *(*apiv1alpha4.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	if err := Convert_v1alpha3_Network_To_v1alpha4_Network(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha4_GCPClusterStatus_To_v1alpha3_GCPClusterStatus(in *v1alpha4.GCPClusterStatus, out *GCPClusterStatus, s conversion.Scope) error {
	out.FailureDomains = *(*apiv1alpha3.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	if err := Convert_v1alpha4_Network_To_v1alpha3_Network(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha3_GCPMachine_To_v1alpha4_GCPMachine(in *GCPMachine, out *v1alpha4.GCPMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_GCPMachineSpec_To_v1alpha4_GCPMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_GCPMachineStatus_To_v1alpha4_GCPMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_GCPMachine_To_v1alpha4_GCPMachine is an autogenerated conversion function.
func Convert_v1alpha3_GCPMachine_To_v1alpha4_GCPMachine(in *GCPMachine, out *v1alpha4.GCPMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPMachine_To_v1alpha4_GCPMachine(in, out, s)
}

func autoConvert_v1alpha4_GCPMachine_To_v1alpha3_GCPMachine(in *v1alpha4.GCPMachine, out *GCPMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_GCPMachineSpec_To_v1alpha3_GCPMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_GCPMachineStatus_To_v1alpha3_GCPMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_GCPMachine_To_v1alpha3_GCPMachine is an autogenerated conversion function.
func Convert_v1alpha4_GCPMachine_To_v1alpha3_GCPMachine(in *v1alpha4.GCPMachine, out *GCPMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPMachine_To_v1alpha3_GCPMachine(in, out, s)
}

func autoConvert_v1alpha3_GCPMachineList_To_v1alpha4_GCPMachineList(in *GCPMachineList, out *v1alpha4.GCPMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.GCPMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_GCPMachine_To_v1alpha4_GCPMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_GCPMachineList_To_v1alpha4_GCPMachineList is an autogenerated conversion function.
func Convert_v1alpha3_GCPMachineList_To_v1alpha4_GCPMachineList(in *GCPMachineList, out *v1alpha4.GCPMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPMachineList_To_v1alpha4_GCPMachineList(in, out, s)
}

func autoConvert_v1alpha4_GCPMachineList_To_v1alpha3_GCPMachineList(in *v1alpha4.GCPMachineList, out *GCPMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_GCPMachine_To_v1alpha3_GCPMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_GCPMachineList_To_v1alpha3_GCPMachineList is an autogenerated conversion function.
func Convert_v1alpha4_GCPMachineList_To_v1alpha3_GCPMachineList(in *v1alpha4.GCPMachineList, out *GCPMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPMachineList_To_v1alpha3_GCPMachineList(in, out, s)
}

func autoConvert_v1alpha3_GCPMachineSpec_To_v1alpha4_GCPMachineSpec(in *GCPMachineSpec, out *v1alpha4.GCPMachineSpec, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	out.Subnet = (*string)(unsafe.Pointer(in.Subnet))
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.ImageFamily = (*string)(unsafe.Pointer(in.ImageFamily))
	out.Image = (*string)(unsafe.Pointer(in.Image))
	out.AdditionalLabels = *(*v1alpha4.Labels)(unsafe.Pointer(&in.AdditionalLabels))
	out.AdditionalMetadata = *(*[]v1alpha4.MetadataItem)(unsafe.Pointer(&in.AdditionalMetadata))
	out.PublicIP = (*bool)(unsafe.Pointer(in.PublicIP))
	out.AdditionalNetworkTags = *(*[]string)(unsafe.Pointer(&in.AdditionalNetworkTags))
	out.RootDeviceSize = in.RootDeviceSize
	out.RootDeviceType = (*v1alpha4.DiskType)(unsafe.Pointer(in.RootDeviceType))
	out.AdditionalDisks = *(*[]v1alpha4.AttachedDiskSpec)(unsafe.Pointer(&in.AdditionalDisks))
	out.ServiceAccount = (*v1alpha4.ServiceAccount)(unsafe.Pointer(in.ServiceAccount))
	out.Preemptible = in.Preemptible
	return nil
}

func autoConvert_v1alpha4_GCPMachineSpec_To_v1alpha3_GCPMachineSpec(in *v1alpha4.GCPMachineSpec, out *GCPMachineSpec, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	out.Subnet = (*string)(unsafe.Pointer(in.Subnet))
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.ImageFamily = (*string)(unsafe.Pointer(in.ImageFamily))
	out.Image = (*string)(unsafe.Pointer(in.Image))
	out.AdditionalLabels = *(*Labels)(unsafe.Pointer(&in.AdditionalLabels))
	out.AdditionalMetadata = *(*[]MetadataItem)(unsafe.Pointer(&in.AdditionalMetadata))
	out.PublicIP = (*bool)(unsafe.Pointer(in.PublicIP))
	out.AdditionalNetworkTags = *(*[]string)(unsafe.Pointer(&in.AdditionalNetworkTags))
	out.RootDeviceSize = in.RootDeviceSize
	out.RootDeviceType = (*DiskType)(unsafe.Pointer(in.RootDeviceType))
	out.AdditionalDisks = *(*[]AttachedDiskSpec)(unsafe.Pointer(&in.AdditionalDisks))
	out.ServiceAccount = (*ServiceAccount)(unsafe.Pointer(in.ServiceAccount))
	out.Preemptible = in.Preemptible
	return nil
}

func autoConvert_v1alpha3_GCPMachineStatus_To_v1alpha4_GCPMachineStatus(in *GCPMachineStatus, out *v1alpha4.GCPMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*v1alpha4.InstanceStatus)(unsafe.Pointer(in.InstanceStatus))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

func autoConvert_v1alpha4_GCPMachineStatus_To_v1alpha3_GCPMachineStatus(in *v1alpha4.GCPMachineStatus, out *GCPMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*InstanceStatus)(unsafe.Pointer(in.InstanceStatus))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

func autoConvert_v1alpha3_GCPMachineTemplate_To_v1alpha4_GCPMachineTemplate(in *GCPMachineTemplate, out *v1alpha4.GCPMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_GCPMachineTemplateSpec_To_v1alpha4_GCPMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_GCPMachineTemplate_To_v1alpha4_GCPMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_GCPMachineTemplate_To_v1alpha4_GCPMachineTemplate(in *GCPMachineTemplate, out *v1alpha4.GCPMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPMachineTemplate_To_v1alpha4_GCPMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_GCPMachineTemplate_To_v1alpha3_GCPMachineTemplate(in *v1alpha4.GCPMachineTemplate, out *GCPMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_GCPMachineTemplateSpec_To_v1alpha3_GCPMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_GCPMachineTemplate_To_v1alpha3_GCPMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_GCPMachineTemplate_To_v1alpha3_GCPMachineTemplate(in *v1alpha4.GCPMachineTemplate, out *GCPMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPMachineTemplate_To_v1alpha3_GCPMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_GCPMachineTemplateList_To_v1alpha4_GCPMachineTemplateList(in *GCPMachineTemplateList, out *v1alpha4.GCPMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.GCPMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_GCPMachineTemplate_To_v1alpha4_GCPMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_GCPMachineTemplateList_To_v1alpha4_GCPMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_GCPMachineTemplateList_To_v1alpha4_GCPMachineTemplateList(in *GCPMachineTemplateList, out *v1alpha4.GCPMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPMachineTemplateList_To_v1alpha4_GCPMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_GCPMachineTemplateList_To_v1alpha3_GCPMachineTemplateList(in *v1alpha4.GCPMachineTemplateList, out *GCPMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_GCPMachineTemplate_To_v1alpha3_GCPMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_GCPMachineTemplateList_To_v1alpha3_GCPMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_GCPMachineTemplateList_To_v1alpha3_GCPMachineTemplateList(in *v1alpha4.GCPMachineTemplateList, out *GCPMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPMachineTemplateList_To_v1alpha3_GCPMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_GCPMachineTemplateResource_To_v1alpha4_GCPMachineTemplateResource(in *GCPMachineTemplateResource, out *v1alpha4.GCPMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_GCPMachineSpec_To_v1alpha4_GCPMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_GCPMachineTemplateResource_To_v1alpha4_GCPMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_GCPMachineTemplateResource_To_v1alpha4_GCPMachineTemplateResource(in *GCPMachineTemplateResource, out *v1alpha4.GCPMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPMachineTemplateResource_To_v1alpha4_GCPMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_GCPMachineTemplateResource_To_v1alpha3_GCPMachineTemplateResource(in *v1alpha4.GCPMachineTemplateResource, out *GCPMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_GCPMachineSpec_To_v1alpha3_GCPMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_GCPMachineTemplateResource_To_v1alpha3_GCPMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_GCPMachineTemplateResource_To_v1alpha3_GCPMachineTemplateResource(in *v1alpha4.GCPMachineTemplateResource, out *GCPMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPMachineTemplateResource_To_v1alpha3_GCPMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_GCPMachineTemplateSpec_To_v1alpha4_GCPMachineTemplateSpec(in *GCPMachineTemplateSpec, out *v1alpha4.GCPMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_GCPMachineTemplateResource_To_v1alpha4_GCPMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_GCPMachineTemplateSpec_To_v1alpha4_GCPMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_GCPMachineTemplateSpec_To_v1alpha4_GCPMachineTemplateSpec(in *GCPMachineTemplateSpec, out *v1alpha4.GCPMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_GCPMachineTemplateSpec_To_v1alpha4_GCPMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_GCPMachineTemplateSpec_To_v1alpha3_GCPMachineTemplateSpec(in *v1alpha4.GCPMachineTemplateSpec, out *GCPMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_GCPMachineTemplateResource_To_v1alpha3_GCPMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_GCPMachineTemplateSpec_To_v1alpha3_GCPMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_GCPMachineTemplateSpec_To_v1alpha3_GCPMachineTemplateSpec(in *v1alpha4.GCPMachineTemplateSpec, out *GCPMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_GCPMachineTemplateSpec_To_v1alpha3_GCPMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_MetadataItem_To_v1alpha4_MetadataItem(in *MetadataItem, out *v1alpha4.MetadataItem, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = (*string)(unsafe.Pointer(in.Value))
	return nil
}

// Convert_v1alpha3_MetadataItem_To_v1alpha4_MetadataItem is an autogenerated conversion function.
func Convert_v1alpha3_MetadataItem_To_v1alpha4_MetadataItem(in *MetadataItem, out *v1alpha4.MetadataItem, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetadataItem_To_v1alpha4_MetadataItem(in, out, s)
}

func autoConvert_v1alpha4_MetadataItem_To_v1alpha3_MetadataItem(in *v1alpha4.MetadataItem, out *MetadataItem, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = (*string)(unsafe.Pointer(in.Value))
	return nil
}

// Convert_v1alpha4_MetadataItem_To_v1alpha3_MetadataItem is an autogenerated conversion function.
func Convert_v1alpha4_MetadataItem_To_v1alpha3_MetadataItem(in *v1alpha4.MetadataItem, out *MetadataItem, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetadataItem_To_v1alpha3_MetadataItem(in, out, s)
}

func autoConvert_v1alpha3_Network_To_v1alpha4_Network(in *Network, out *v1alpha4.Network, s conversion.Scope) error {
	out.SelfLink = (*string)(unsafe.Pointer(in.SelfLink))
	out.FirewallRules = *(*map[string]string)(unsafe.Pointer(&in.FirewallRules))
	out.Router = (*string)(unsafe.Pointer(in.Router))
	out.APIServerAddress = (*string)(unsafe.Pointer(in.APIServerAddress))
	out.APIServerHealthCheck = (*string)(unsafe.Pointer(in.APIServerHealthCheck))
	out.APIServerInstanceGroups = *(*map[string]string)(unsafe.Pointer(&in.APIServerInstanceGroups))
	out.APIServerBackendService = (*string)(unsafe.Pointer(in.APIServerBackendService))
	out.APIServerTargetProxy = (*string)(unsafe.Pointer(in.APIServerTargetProxy))
	out.APIServerForwardingRule = (*string)(unsafe.Pointer(in.APIServerForwardingRule))
	return nil
}

// Convert_v1alpha3_Network_To_v1alpha4_Network is an autogenerated conversion function.
func Convert_v1alpha3_Network_To_v1alpha4_Network(in *Network, out *v1alpha4.Network, s conversion.Scope) error {
	return autoConvert_v1alpha3_Network_To_v1alpha4_Network(in, out, s)
}

func autoConvert_v1alpha4_Network_To_v1alpha3_Network(in *v1alpha4.Network, out *Network, s conversion.Scope) error {
	out.SelfLink = (*string)(unsafe.Pointer(in.SelfLink))
	out.FirewallRules = *(*map[string]string)(unsafe.Pointer(&in.FirewallRules))
	out.Router = (*string)(unsafe.Pointer(in.Router))
	out.APIServerAddress = (*string)(unsafe.Pointer(in.APIServerAddress))
	out.APIServerHealthCheck = (*string)(unsafe.Pointer(in.APIServerHealthCheck))
	out.APIServerInstanceGroups = *(*map[string]string)(unsafe.Pointer(&in.APIServerInstanceGroups))
	out.APIServerBackendService = (*string)(unsafe.Pointer(in.APIServerBackendService))
	out.APIServerTargetProxy = (*string)(unsafe.Pointer(in.APIServerTargetProxy))
	out.APIServerForwardingRule = (*string)(unsafe.Pointer(in.APIServerForwardingRule))
	return nil
}

// Convert_v1alpha4_Network_To_v1alpha3_Network is an autogenerated conversion function.
func Convert_v1alpha4_Network_To_v1alpha3_Network(in *v1alpha4.Network, out *Network, s conversion.Scope) error {
	return autoConvert_v1alpha4_Network_To_v1alpha3_Network(in, out, s)
}

func autoConvert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(in *NetworkSpec, out *v1alpha4.NetworkSpec, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.AutoCreateSubnetworks = (*bool)(unsafe.Pointer(in.AutoCreateSubnetworks))
	out.Subnets = *(*v1alpha4.Subnets)(unsafe.Pointer(&in.Subnets))
	out.LoadBalancerBackendPort = (*int32)(unsafe.Pointer(in.LoadBalancerBackendPort))
	return nil
}

func autoConvert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(in *v1alpha4.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.AutoCreateSubnetworks = (*bool)(unsafe.Pointer(in.AutoCreateSubnetworks))
	out.Subnets = *(*Subnets)(unsafe.Pointer(&in.Subnets))
	out.LoadBalancerBackendPort = (*int32)(unsafe.Pointer(in.LoadBalancerBackendPort))
	return nil
}

func autoConvert_v1alpha3_ServiceAccount_To_v1alpha4_ServiceAccount(in *ServiceAccount, out *v1alpha4.ServiceAccount, s conversion.Scope) error {
	out.Email = in.Email
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	return nil
}

// Convert_v1alpha3_ServiceAccount_To_v1alpha4_ServiceAccount is an autogenerated conversion function.
func Convert_v1alpha3_ServiceAccount_To_v1alpha4_ServiceAccount(in *ServiceAccount, out *v1alpha4.ServiceAccount, s conversion.Scope) error {
	return autoConvert_v1alpha3_ServiceAccount_To_v1alpha4_ServiceAccount(in, out, s)
}

func autoConvert_v1alpha4_ServiceAccount_To_v1alpha3_ServiceAccount(in *v1alpha4.ServiceAccount, out *ServiceAccount, s conversion.Scope) error {
	out.Email = in.Email
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	return nil
}

// Convert_v1alpha4_ServiceAccount_To_v1alpha3_ServiceAccount is an autogenerated conversion function.
func Convert_v1alpha4_ServiceAccount_To_v1alpha3_ServiceAccount(in *v1alpha4.ServiceAccount, out *ServiceAccount, s conversion.Scope) error {
	return autoConvert_v1alpha4_ServiceAccount_To_v1alpha3_ServiceAccount(in, out, s)
}

func autoConvert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(in *SubnetSpec, out *v1alpha4.SubnetSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.SecondaryCidrBlocks = *(*map[string]string)(unsafe.Pointer(&in.SecondaryCidrBlocks))
	out.Region = in.Region
	out.PrivateGoogleAccess = (*bool)(unsafe.Pointer(in.PrivateGoogleAccess))
	out.EnableFlowLogs = (*bool)(unsafe.Pointer(in.EnableFlowLogs))
	return nil
}

// Convert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(in *SubnetSpec, out *v1alpha4.SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(in, out, s)
}

func autoConvert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(in *v1alpha4.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.SecondaryCidrBlocks = *(*map[string]string)(unsafe.Pointer(&in.SecondaryCidrBlocks))
	out.Region = in.Region
	out.PrivateGoogleAccess = (*bool)(unsafe.Pointer(in.PrivateGoogleAccess))
	out.EnableFlowLogs = (*bool)(unsafe.Pointer(in.EnableFlowLogs))
	return nil
}

// Convert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(in *v1alpha4.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(in, out, s)
}
